graph TD
    BB_0["BB_0\nt1 = "Hello, World!. Enter some symbol"\ns = t1\nt2 = call puts(s)\nt5 = call getchar()\nc = t5\nt6 = call putchar(c)\nt9 = 10\nt8 = call putchar(t9)\nt11 = "%d"\nt12 = 10\nt10 = call printf(t11, t12)\nt14 = 10\nt13 = call putchar(t14)\nt15 = 27\nreturn t15\n"]
