graph TD;
N0["source"]
N1["source_item"]
N0 --> N1
N2["func_definition"]
N1 --> N2
N3["def"]
N2 --> N3
N4["func_signature"]
N2 --> N4
N5["identifier: main"]
N4 --> N5
N6["("]
N4 --> N6
N7[")"]
N4 --> N7
N8["of"]
N4 --> N8
N9["type_ref"]
N4 --> N9
N10["builtin_type"]
N9 --> N10
N11["int"]
N10 --> N11
N12["statement"]
N2 --> N12
N13["expression_statement"]
N12 --> N13
N14["expr"]
N13 --> N14
N15["binary_expr"]
N14 --> N15
N16["expr"]
N15 --> N16
N17["identifier: s"]
N16 --> N17
N18["="]
N15 --> N18
N19["expr"]
N15 --> N19
N20["literal"]
N19 --> N20
N21["str: "Hello, World!. Enter some symbol""]
N20 --> N21
N22[";"]
N13 --> N22
N23["comment"]
N2 --> N23
N24["statement"]
N2 --> N24
N25["expression_statement"]
N24 --> N25
N26["expr"]
N25 --> N26
N27["binary_expr"]
N26 --> N27
N28["expr"]
N27 --> N28
N29["identifier: c"]
N28 --> N29
N30["="]
N27 --> N30
N31["expr"]
N27 --> N31
N32["literal"]
N31 --> N32
N33["dec: 10"]
N32 --> N33
N34[";"]
N25 --> N34
N35["statement"]
N2 --> N35
N36["return_statement"]
N35 --> N36
N37["return"]
N36 --> N37
N38["expr"]
N36 --> N38
N39["identifier: c"]
N38 --> N39
N40[";"]
N36 --> N40
N41["end"]
N2 --> N41
